### PR TITLE
Add more examples of invisible elements

### PR DESCRIPTION
**Pull request by Jym77**
At today's [CG call](https://www.w3.org/2022/03/24-act-r-minutes.html#item05) we decide that we should have more examples of ways of making things invisible. Even if the examples here are not normative.
It would be better to sprinkle such cases in various actual rule so that implementers can actually test them, but that is more complex. Having an example list is at least useful for implementers needing inspiration on cases they may want to handle.

Closes issue(s):

- N/A

Need for Call for Review:
This will require a 1 week Call for Review (adding more non-normative examples)

---

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [X] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Review by HelenBurge — APPROVED** [review]

**Review by WilcoFiers — COMMENTED** [review]
I'm not sure I see the value in doing this, but I don't mind them either.

**Comment by Jym77** [comment]
Call for Review ends on May 19th.

**Review by colabottles — APPROVED** [review]

**Review by bruce-usab — APPROVED** [review]
Thanks for making the sample text a little different from each other!

I am not sure where it might be added, but I'll suggest making it explicit that the idea is that text which not presented to users be implemented in a way that it can be ignored by assistive technology, and these are examples of that.

**Comment by Jym77** [comment]
Call for review has ended. Merging.

**Pull request merged**
