### PR TITLE
test: add tests to verify h4 headings

### PR DESCRIPTION
**Pull request by jkodu**
Tests to ensure:
- No duplicate test case headings are used eg: Passed Example 1, Passed Example 1.
- Case sensitivity & language used for test case heading.
- File to review is here - https://github.com/act-rules/act-rules.github.io/pull/810/files#diff-b32eec93e3bb3b26b825603aad696899
- Fixed all failing test cases

Closes issue(s): 
- (ADD ISSUE NUMBER HERE)

----

### **When creating PR:**
- Make sure you requesting to **pull a branch** (right side) to the `develop` branch (left side).

### **After creating PR:**
- Add yourself (and co-authors) as "Assignees" for PR.
- Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- Close the issue that the PR resolves (and make sure the issue is referenced in the top of this comment)
- Optionally request feedback from anyone in particular by assigning them as "Reviewers".

## How to Review And Approve
- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines. 
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.

### CODE REVIEW

**Comment by Jym77** [comment]
By the way, would it be possible/easy to split the tests in several Circle steps?

Currently, there's one big step in the test job and when some tests are failing it's often a pretty big scroll down the list to figure out which one. With smaller steps, we could immediately see which ones are failing and see relevant information faster.

**Comment by jkodu** [comment]
I have been thinking about this @Jym77. Let's discuss in today's call. It is an easy thing to do in Circle.

**Comment by jkodu** [comment]
TODO to self @jkodu 

Split tests by category:
- test/rules
- test/glossary
- test/build/implementations

**Comment by jkodu** [comment]
@Jym77 - I have created an issue https://github.com/act-rules/act-rules.github.io/issues/820 for splitting CI.

Otherwise this PR is ready.

**Pull request merged**
