### PR TITLE
Hide content using left rather than top positioning

### LINKED ISSUE #1776: Consider not hiding content with `top`
We have a few rules that are making content invisible with `position: absolute; top: -9999px`.

As far as I'm reading, using `top` is not a very good practice because (i) if used on an element high enough, or whose offset ancestor is low enough, it won't hide it fully;  and (ii) if used on focusable content, it may causes the page to jump back and forth when trying to scroll to the element.

None of these problems occurs in our examples because they are so small. Nonetheless, we might want to not show this poor practice and instead hide stuff with `left: -9999px` which is safer. Notably because people might consider what we write as examples to follow.

### PR DESCRIPTION
**Pull request by Jym77**
Use `position: absolute; left: -9999px` to visually hide content, rather than `top: …` which is not so good practice.

Closes issue(s):

- closes #1776

Need for Call for Review:
This will require a 1 week Call for Review (superficially changing some test cases)

---

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [X] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [X] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Review by tbostic32 — APPROVED** [review]

**Review by carlosapaduarte — APPROVED** [review]

**Review by WilcoFiers — CHANGES_REQUESTED** [review]
I'm not quite understanding why this is necessary. An element that's off screen is off screen. If it's off the top, the implementor needs to check that the content is far enough off the top that it's actually hidden. If it's off to the left, same thing.

Even if left is a better technique in CSS for content authors to use, shouldn't implementors know to consider both of them? Not immediately against this, but I'd like to understand it better before it goes forward.

**Comment by Jym77** [comment]
> Not immediately against this, but I'd like to understand it better before it goes forward.

It is a matter of showcasing better practice since our code might be used as example of "things to do".

**Comment by WilcoFiers** [comment]
@Jym77 Should we put this on the agenda?

**Comment by Jym77** [comment]
[CG call summary](https://www.w3.org/2022/03/24-act-r-minutes.html#item05): we do not care about having best practices example only; our examples are meant to exercice corner cases. Therefore we close this PR (and issue).
We should add some more (in)visibility examples; possibly sprinkling some over all rules.

**Pull request closed without merging**
