### PR TITLE
Update heading-non-empty-accessible-name-ffd0e9.md

### LINKED ISSUE #1639: SC 2.4.6 for Heading has non-empty accessible name
[Rule Id: ffd0e9](https://act-rules.github.io/rules/ffd0e9)

From [Understanding 2.4.6](https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html): This Success Criterion requires that if headings or labels are provided, they be descriptive.

I don't think 2.4.6 should be included in this rule.

### PR DESCRIPTION
**Pull request by kengdoj**
Remove 2.4.6 from Accessibility Requirements

Closes issue(s):

- closes #1639

Need for Final Call:
*edit:* This will require a 2 week Final Call - change to Accessibility Requirements.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Review by carlosapaduarte — CHANGES_REQUESTED** [review]
The reference to 2.4.6 should also be removed from the Background section.

Keep in mind that changes to the Accessibility Requirements are not editorial and *do* require a 2 weeks final call.

**Comment by kengdoj** [comment]
Thanks, @carlosapaduarte, I made an additional edit to remove 2.4.6 from the Background. 

Sorry, I selected the wrong final call option. Should I change it in the first comment?

**Review by carlosapaduarte — APPROVED** [review]
Yes, probably better to change the original comment to update the final call reference.

**Comment by kengdoj** [comment]
ok, edit made and marked.

**Review by WilcoFiers — APPROVED** [review]

**Review by ajanec01 — APPROVED** [review]

**Review by ajanec01 — DISMISSED** [review]
You also need to remove line 196 ([usc246]:  https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html 'Understanding Success Criterion 2.4.6: Headings and Labels') for the tests to pass.

**Review by ajanec01 — APPROVED** [review]

**Comment by kengdoj** [comment]
Thanks for pointing that out, @ajanec01.

**Review by colabottles — APPROVED** [review]

**Pull request merged**
