### PR TITLE
Add "non-empty" before xml:lang under Applicability (5b7ae0)

### PR DESCRIPTION
**Pull request by kengdoj**
Inapplicable Example 3 states the rule mandates non-empty values.

### CODE REVIEW

**Comment by jkodu** [comment]
@kengdoj can you please sign the CLA. The button in this comment, should help you do this.

> Note to all: Final call finishes on 05 November 2019

**Comment by Jym77** [comment]
> > Note to all: Final call finishes on 05 November 2019

@jkodu had this gone to FC? If so, can you put the label?

**Comment by jkodu** [comment]
> Note: Emailed @kengdoj & awaiting CLA to be signed.

**Comment by jkodu** [comment]
@Jym77 I am unsure if FC is essential for this change. I do not see an email for the same.

**Comment by Jym77** [comment]
@jkodu https://github.com/act-rules/act-rules.github.io/pull/1000#pullrequestreview-308871949

**Comment by jkodu** [comment]
Final call Ends on November 13, 2019.

**Pull request merged**
