### PR TITLE
table-header-has-assigned-cells: Remove H43 from mapping

### LINKED ISSUE #1626: [Quick Review] Table header cell has assigned cells
Rule Link: [Table header cell has assigned cells](https://act-rules.github.io/rules/d0f69e)

I am finding it hard to understand why technique [H43 Using id and headers attributes to associate data cells with header cells in data tables ](https://www.w3.org/WAI/WCAG21/Techniques/html/H43) is included in the accessibility requirements since it seems only applicable to passed example 5. In other words, if Passed Example 1 fails it seems like a bit of a stretch to me to consider H43 also failed as is stated in the requirements mapping. 

If we do follow the same logic, I might also expect [H51: Using table markup to present tabular information](https://www.w3.org/WAI/WCAG21/Techniques/html/H51) and [H63: Using the scope attribute to associate header cells and data cells in data tables](https://www.w3.org/WAI/WCAG21/Techniques/html/H63) to be included since they follow a similar format of having specific examples very relevant for them.

### PR DESCRIPTION
**Pull request by WilcoFiers**
Closes #1626

Need for Final Call: 2 weeks

----

eview And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Review by daniel-montalvo — APPROVED** [review]

**Review by carlosapaduarte — CHANGES_REQUESTED** [review]
Should remove H43 from the Background section also.

**Comment by carlosapaduarte** [comment]
And shouldn't changing accessibility requirements be a 2 week final call?

**Comment by carlosapaduarte** [comment]
I believe you didn't push your changes. At least I'm still seeing the reference to H43 in the background section.

**Review by ajanec01 — APPROVED** [review]

**Comment by ajanec01** [comment]
Isn't that ok to keep the technique in the background section? Seems fine with the [description of the background section](https://act-rules.github.io/pages/design/rule-design/#background) on the rule design page.

**Review by Jym77 — APPROVED** [review]

**Review by annethyme — APPROVED** [review]

**Pull request merged**
