### PR TITLE
"Id attribute value is unique" (3ea0c8): Add title to iframe in example

### PR DESCRIPTION
**Pull request by Jym77**
Add a title to the iframe in an example, to make it better code practice.

Closes issue(s):

- partial for https://github.com/w3c/wcag-act/issues/426

Need for Final Call:
This will require a 1 week Final Call (updating one example).

---

### **When creating PR:**

- Make sure you requesting to **pull a branch** (right side) to the `develop` branch (left side).

### **After creating PR:**

- Add yourself (and co-authors) as "Assignees" for PR.
- Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- Close the issue that the PR resolves (and make sure the issue is referenced in the top of this comment)
- Optionally request feedback from anyone in particular by assigning them as "Reviewers".

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Comment by Jym77** [comment]
> I am approving this as this has a clear scope and rationale. However, in the explanatory paragraph for some of the test cases we have.
> 
> > ### Passed Example 2
> > 
> > * All ids are unique within the document context.
> > 
> > Passed Example 3
> > 
> > * Two of the id are the same (my-elt), but they are in different trees (the first one in the document tree and the second in the shadow tree).
> 
> It seems we are missing the plural form (ids( for some instances in this rule.
> 
> > Passed Example 4
> > Both id are the same (my-elt), but they are in different document trees because the iframe is creating a new one.
> 
> Do you all agree that these should be updated?
> 
> If so, I can take care of it in another pull request.

I will add that to #1150. Thanks.

**Comment by Jym77** [comment]
Final Call ends on February 11.

**Comment by EmmaJP** [comment]
As per my comments on #1150, I think `id` can be considered implicitly plural, especially when marked as a code snippet. It feels nicer to use `id` attributes, with the plural on attribute, rather than `id`s. 

act-rule usage is almost exclusively referring to `id` as an attribute of an element and not I.D. as an acronym.

**Comment by Jym77** [comment]
Final Call has ended. Merging.

**Pull request merged**
