### PR TITLE
Remove 2nd WCAG reference: 1.4.10

### PR DESCRIPTION
**Pull request by HelenBurge**
Removed 1.4.10 as zoom restrictions are easier to note with 1.4.4

Closes issue(s):

N/A

Need for Call for Review:
This will require a 1 week Call for Review

### CODE REVIEW

**Review by WilcoFiers — APPROVED** [review]

**Review by daniel-montalvo — APPROVED** [review]

**Review by daniel-montalvo — APPROVED** [review]

**Review by tbostic32 — APPROVED** [review]

**Review by colabottles — APPROVED** [review]

**Review by carlosapaduarte — APPROVED** [review]

**Comment by carlosapaduarte** [comment]
@HelenBurge have you sent the email to the mailing list announcing the 1 week call for review?

**Comment by HelenBurge** [comment]
> @HelenBurge have you sent the email to the mailing list announcing the 1 week call for review?

@carlosapaduarte I sent it yesterday and then added the label?

**Comment by carlosapaduarte** [comment]
Weird... I can't find your email in any of my inboxes and spam folders...

**Comment by HelenBurge** [comment]
> Weird... I can't find your email in any of my inboxes and spam folders...

I forwarded what I sent to your email - maybe I did it to the wrong group?

**Pull request merged**
