### PR TITLE
Updated examples to ensure tests are case insensitive in valid lang tag rules

### LINKED ISSUE #1499: Add test case with different capitalization in valid language tag rules (de46e4 and bf051a)
I have found a bug in an implementation of the rule "Element with lang attribute has valid language tag" (de46e4) that has to do with the implementation only accepting a certain capitalization in language tags. 
According to the implementation report, this tool had a correct implementation, so I suggest adding a new test case with different capitalization (e.g. lang="EN") to ensure consistency in implementations in this area.

The same applies to the rule "HTML page lang attribute has valid language tag" (bf051a).

### PR DESCRIPTION
**Pull request by carlosapaduarte**
…subtag are done in a case insensitive manner

Closes issue(s):

- closes #1499 

Need for Call for Review:
This will require a 1 week Call for Review

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Review by Jym77 — DISMISSED** [review]
Not fully sure whether we should instead add new passed example (with appropriate description pointing on case insensitivity).
Mostly because these examples probably already exist for a reason (at least I hope) and that they now have 2 reasons: the old one and the case insensitivity; which we normally frown upon.

**Comment by carlosapaduarte** [comment]
The definition of valid language tag already includes this:
> Subtags, notably the primary language subtag, are case insensitive. Hence comparison with the language subtag registry must be done in a case insensitive way.

Do you really think that we need to have tests exclusively checking this?

**Review by Jym77 — APPROVED** [review]

**Review by WilcoFiers — APPROVED** [review]
@carlosapaduarte can you change the PR title of this, so we end up with a complete message in the changelog?

**Review by daniel-montalvo — APPROVED** [review]

**Comment by carlosapaduarte** [comment]
Call for review ends on February 18

**Review by colabottles — APPROVED** [review]

**Comment by carlosapaduarte** [comment]
Call for review ended. Merging

**Pull request merged**
