### PR TITLE
Definition of Programmatically Determinable

### PR DESCRIPTION
**Pull request by ajanec01**
The definition of programmatically determinable on the accessibility support page lists criteria to which it applies. It should also include SC 1.3.5 Identify Input Purpose.

I've added SC 1.3.5 to the list of criteria the programmatically determinable term applies.

Need for Final Call:
This can be merged with 1 approval (editorial changes to the  website)

---

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Comment by ajanec01** [comment]
Thanks! My first time using GitHub. Please give a shout if I've done something wrong or something needs re-adjustment.

**Comment by Jym77** [comment]
@ajanec01 Do you want to do the merge or should I handle it?

**Comment by ajanec01** [comment]
Hey @Jym77, I don't think I have the rights to do the merge. Would you be able to do it?

**Comment by ajanec01** [comment]
Thanks @Jym77 !  I don't think I have the rights to do the merge, or do I?

**Comment by Jym77** [comment]
No, you probably don't have writing rights, indeed.

**Pull request merged**
