### PR TITLE
Move file to _rules folder

### PR DESCRIPTION
**Pull request by carlosapaduarte**
File for rule "Object element has non-empty accessible name" was in the wrong place. Moving it to the _rules folder.

Need for Final Call:
This will not require a Final Call (change to website: just moving a file with any editing)

### CODE REVIEW

**Comment by jkodu** [comment]
Yikes. I am surprised we missed this in the pull request reviews :/

**Comment by jkodu** [comment]
@carlosapaduarte there are failing tests - https://github.com/act-rules/act-rules.github.io/pull/1324/checks?check_run_id=717080152

**Comment by carlosapaduarte** [comment]
@jkodu me too! Can you have a look at the failing test? I can't get what is going on with that

**Comment by carlosapaduarte** [comment]
@jkodu don't know why I couldn't see the full test rusults yesterdat (that's why I couldn't make sense of the report). Now I can and the typo has been fixed. Could you please review again?

**Pull request merged**
