### PR TITLE
Revert "Remove 2nd WCAG reference: 1.4.10"

### PR DESCRIPTION
**Pull request by HelenBurge**
Reverts act-rules/act-rules.github.io#1756

### CODE REVIEW

**Review by WilcoFiers — APPROVED** [review]

**Review by JenniferChadwick — APPROVED** [review]

**Review by wcreedle — APPROVED** [review]

**Review by kengdoj — APPROVED** [review]

**Review by Jym77 — APPROVED** [review]

**Comment by patrickhlauke** [comment]
Most (all?) browsers on mobile/tablet don't do reflow when zooming, so not sure how these are related?

**Comment by WilcoFiers** [comment]
@patrickhlauke That's an interesting point. Are you saying that because mobile browsers don't reflow when you zoom anyway, preventing zoom isn't a violation of the reflow SC? That's not an angle I had considered.

What does that mean for 1.4.10 reflow in relation to mobile sites? Do those just fail because mobile browsers don't reflow when you zoom, or is it simply not appropriate to test 1.4.10 if you're only targeting browsers that can't reflow in the first place?

**Comment by patrickhlauke** [comment]
1.4.10 is certainly related/dependent on the ability to zoom or resize the browser/viewport (to reach the 320 CSS px mark for vertical scrolling / 256 CSS px for horizontal scrolling content, which is normatively the only size at which reflow needs to pass - which is a problem in its own right, see https://github.com/w3c/wcag/issues/698). *but* if you can't resize, it doesn't fail 1.4.10 because normatively that SC doesn't say "you must be able to resize to that viewport size". that scenario fails 1.4.4 Resize Text, but not 1.4.10 Reflow.

now on the separate point, 1.4.10 itself can't really be tested on most (practically all, with a few exotic outliers) mobile/tablet OS browsers, since they simply don't reflow. See https://www.w3.org/WAI/WCAG21/Understanding/reflow.html#browsers-on-mobile-operating-systems

**Comment by WilcoFiers** [comment]
@patrickhlauke Thanks for your thoughts. I'll take this back to the ACT Task Force next week. I think you've convinced me. Let me see what the rest thinks.

**Comment by HelenBurge** [comment]
As no longer viable

**Pull request closed without merging**
