### PR TITLE
Replace autocomplete value with a failing value

### LINKED ISSUE #1667: autocomplete attribute has valid value 73f2c2 - inapplicable test cases
I think the inapplicable test cases that currently use `autocomplete="username"` would be better if they used an value that would cause a failure like `autocomplete="badterm"`

Otherwise I think a tool can get the applicability wrong and still pass all the test cases.

### PR DESCRIPTION
**Pull request by colabottles**
Replacing the autocomplete="username" with a value that will fail. e.g.: autocomplete="user"

Changed Failed Example 1 from `<input autocomplete="badterm"/></label>` to `<label>Username<input autocomplete="user"/></label>`

Closes issue(s):

- closes #1667 

Need for Final Call: 1 week

---

### **When creating PR:**

- [x] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [x] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [x] Add yourself (and co-authors) as "Assignees" for PR.
- [x] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [x] [Link the PR to any issue it solves](https://github.com/act-rules/act-rules.github.io/issues/1667).
- [x] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Comment by colabottles** [comment]
@WilcoFiers Following up here also. Changed the mistake, edited the correct examples.

**Review by WilcoFiers — APPROVED** [review]

**Comment by dd8** [comment]
Shouldn't Inapplicable Example 6 also be changed to use autocomplete="badname"?

```
<label>Username<input type="text" role="none" disabled autocomplete="username"/></label>
```

**Review by ajanec01 — CHANGES_REQUESTED** [review]
We should go with 'badname' for Inapplicable example 6 as well, as per @dd8's comment.

**Comment by colabottles** [comment]
Changes have been made to reflect @dd8 comment and inapplicable example 6 should read `badname` instead of `username`. I have asked for a re-review from @ajanec01 and @WilcoFiers as well. Thanks.

**Review by ajanec01 — APPROVED** [review]

**Review by carlosapaduarte — APPROVED** [review]

**Review by WilcoFiers — APPROVED** [review]

**Review by WilcoFiers — CHANGES_REQUESTED** [review]
Actually, no I think this needs a 1 week call for review. The rest is fine, but I don't think this is editorial.

**Review by kengdoj — APPROVED** [review]
Thanks, @colabottles!

**Review by Jym77 — APPROVED** [review]

**Review by WilcoFiers — APPROVED** [review]

**Pull request merged**
