### PR TITLE
Remove outdated class="target" from examples (b49b2e / a1b64e / ebe86a / 80af7b)

### PR DESCRIPTION
**Pull request by Jym77**
Some examples in a few rules still had a `class="target"` which was apparently an abandonned attempt to auto-highlight them in rule pages. Cleaning them up.

Closes issue(s):

- N/A

Need for Final Call:
This will require a 1 week Final Call (updating several examples, even though changes are editorial only…)

---

### **When creating PR:**

- [x] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).

### **After creating PR:**

- [x] Add yourself (and co-authors) as "Assignees" for PR.
- [x] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] Close the issue that the PR resolves (and make sure the issue is referenced in the top of this comment)
- [x] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Comment by adilsofficial** [comment]
In rule 80af7b Passed and Failed example 4 and 5, and rule ebe864a Passed and Failed example 1 and 2 still have `class="target"`. Is there special reason behind keeping this attribute in these example?

**Comment by Jym77** [comment]
Good catch @adilsofficial My replacement pattern was tailored for when it appear in the middle of a line, not alone on a line of itself 😞

**Comment by Jym77** [comment]
> This change is going to invalidate some implementations.

Yes.
1. Do you think it is better to wait until the rule is submitted to the TF and the TF asks us to remove this, thus invalidating the implementation later and delaying the publication even more?
2. We just decided to invalidate all implementations (https://www.w3.org/2020/02/27-act-r-minutes.html#item03) anyway…

**Comment by jkodu** [comment]
Need to lose also `data-rule-target` - https://github.com/act-rules/act-rules.github.io/search?q=data-rule-target&unscoped_q=data-rule-target

**Pull request merged**
