### PR TITLE
ARIA required owned elm; fix parser issue in pass 3

### PR DESCRIPTION
**Pull request by WilcoFiers**
Browsers only allow `th` and `td` elements as children of `tr`. The `span` we used in passed example 3 gets booted out by the browser, and is instead rendered above the table inside the DOM tree. If you inspect the DOM of this code example, it'll look like this:

- `<body>`
    - `<span role="cell">`
    - `<table role="grid">`
        - `<tbody>`
            - `<tr role="row">`

Wrapping the span in a td with role=none should fix the issue, and I think, preserve the intent of the example.

Need for Call for Review: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Comment by Jym77** [comment]
This should close #1552. Can you link it from the description?

**Review by daniel-montalvo — DISMISSED** [review]

**Review by HelenBurge — APPROVED** [review]

**Comment by tombrunet** [comment]
I'm having a hard time resolving Pass 3 as a good example when it conflicts with the ARIA in HTML guidance - https://www.w3.org/TR/html-aria/#docconformance . The ARIA in HTML group noted that role may not be used on table elements within a table, grid, or treegrid. They had approached us about flagging role on these elements as violations. I think the redundant "row" role is less of an issue than the td with role="none".

**Review by colabottles — APPROVED** [review]

**Comment by scottaohara** [comment]
This allowance would require some bugs to be filed to make it work consistently across browsers/AT pairings. Results in codepen from testing this morning.
https://codepen.io/scottohara/pen/poapLqW

**Review by tombrunet — DISMISSED** [review]
See Scott's codepen notes. There are several browser/AT combinations that don't support this.

**Review by tombrunet — APPROVED** [review]

**Review by HelenBurge — APPROVED** [review]

**Review by Jym77 — APPROVED** [review]

**Review by colabottles — APPROVED** [review]

**Review by carlosapaduarte — APPROVED** [review]

**Pull request merged**
